const X_LIMIT = 80;
const Y_LIMIT = 30;

const CUR_OFFSET = 1;
const NEXT_OFFSET = 2;

const SCREEN_LARGE = 1200;
const SCREEN_MEDIUM = 1000;
const SCREEN_SMALL = 620;

const LOWER_CACHELIMIT = 1;

export {
	X_LIMIT,
	Y_LIMIT,
	CUR_OFFSET,
	NEXT_OFFSET,
	SCREEN_LARGE,
	SCREEN_MEDIUM,
	SCREEN_SMALL,
	LOWER_CACHELIMIT
};